"""Ontology validation error-code constants (Sprint 6; reusable by Sprint 7+)."""

from __future__ import annotations

VOCAB_SEED_HASH_MISMATCH = "VOCAB_SEED_HASH_MISMATCH"
ONTOLOGY_SEED_HASH_MISMATCH = "ONTOLOGY_SEED_HASH_MISMATCH"
VOCAB_INCOMPLETE = "VOCAB_INCOMPLETE"
VOCAB_EXTRA = "VOCAB_EXTRA"
VOCAB_TYPE_MISMATCH = "VOCAB_TYPE_MISMATCH"
VOCAB_INACTIVE = "VOCAB_INACTIVE"
ONT_ID_MISMATCH = "ONT_ID_MISMATCH"
MISSING_REQUIRED_ONTOLOGY = "MISSING_REQUIRED_ONTOLOGY"
DUPLICATE_ONTOLOGY = "DUPLICATE_ONTOLOGY"
MISSING_FIELD = "MISSING_FIELD"
INVALID_CARDINALITY = "INVALID_CARDINALITY"
INVALID_VOCAB_REF = "INVALID_VOCAB_REF"
INVALID_OBJECT_REF = "INVALID_OBJECT_REF"
OBJECT_NOT_FOUND = "OBJECT_NOT_FOUND"
FREE_TEXT_CLASSIFICATION = "FREE_TEXT_CLASSIFICATION"
CONFIDENCE_NOT_NULL = "CONFIDENCE_NOT_NULL"
INVALID_CLASSIFICATION_SOURCE = "INVALID_CLASSIFICATION_SOURCE"
UNSORTED_MULTI = "UNSORTED_MULTI"
ONTOLOGY_VERSION_MISMATCH = "ONTOLOGY_VERSION_MISMATCH"

ALL_ERROR_CODES: frozenset[str] = frozenset(
    {
        VOCAB_SEED_HASH_MISMATCH,
        ONTOLOGY_SEED_HASH_MISMATCH,
        VOCAB_INCOMPLETE,
        VOCAB_EXTRA,
        VOCAB_TYPE_MISMATCH,
        VOCAB_INACTIVE,
        ONT_ID_MISMATCH,
        MISSING_REQUIRED_ONTOLOGY,
        DUPLICATE_ONTOLOGY,
        MISSING_FIELD,
        INVALID_CARDINALITY,
        INVALID_VOCAB_REF,
        INVALID_OBJECT_REF,
        OBJECT_NOT_FOUND,
        FREE_TEXT_CLASSIFICATION,
        CONFIDENCE_NOT_NULL,
        INVALID_CLASSIFICATION_SOURCE,
        UNSORTED_MULTI,
        ONTOLOGY_VERSION_MISMATCH,
    }
)
