"""Query error codes (Sprint 9)."""

from __future__ import annotations

QUERY_EMPTY = "QUERY_EMPTY"
QUERY_MALFORMED = "QUERY_MALFORMED"
QUERY_UNKNOWN_FIELD = "QUERY_UNKNOWN_FIELD"
QUERY_EMPTY_VALUE = "QUERY_EMPTY_VALUE"
QUERY_NL_FORBIDDEN = "QUERY_NL_FORBIDDEN"
QUERY_FUZZY_FORBIDDEN = "QUERY_FUZZY_FORBIDDEN"
QUERY_INVALID_STATUS = "QUERY_INVALID_STATUS"
QUERY_INVALID_VALIDATION = "QUERY_INVALID_VALIDATION"
QUERY_VOCAB_UNRESOLVED = "QUERY_VOCAB_UNRESOLVED"
QUERY_VOCAB_INACTIVE = "QUERY_VOCAB_INACTIVE"
QUERY_OPERATOR_AMBIGUOUS = "QUERY_OPERATOR_AMBIGUOUS"
QUERY_OPERATOR_UNRESOLVED = "QUERY_OPERATOR_UNRESOLVED"
QUERY_PRIMITIVE_AMBIGUOUS = "QUERY_PRIMITIVE_AMBIGUOUS"
QUERY_PRIMITIVE_UNRESOLVED = "QUERY_PRIMITIVE_UNRESOLVED"
QUERY_SUBJECT_AMBIGUOUS = "QUERY_SUBJECT_AMBIGUOUS"
QUERY_SUBJECT_REQUIRED = "QUERY_SUBJECT_REQUIRED"
QUERY_FRR_MISSING = "QUERY_FRR_MISSING"
QUERY_FEATURE_MISSING = "QUERY_FEATURE_MISSING"
QUERY_NOT_FOUND = "QUERY_NOT_FOUND"
QUERY_MATCH_ALL_CONFLICT = "QUERY_MATCH_ALL_CONFLICT"
QUERY_INTERNAL = "QUERY_INTERNAL"
QUERY_DB_NOT_READY = "QUERY_DB_NOT_READY"

ALL_CODES: frozenset[str] = frozenset(
    {
        QUERY_EMPTY,
        QUERY_MALFORMED,
        QUERY_UNKNOWN_FIELD,
        QUERY_EMPTY_VALUE,
        QUERY_NL_FORBIDDEN,
        QUERY_FUZZY_FORBIDDEN,
        QUERY_INVALID_STATUS,
        QUERY_INVALID_VALIDATION,
        QUERY_VOCAB_UNRESOLVED,
        QUERY_VOCAB_INACTIVE,
        QUERY_OPERATOR_AMBIGUOUS,
        QUERY_OPERATOR_UNRESOLVED,
        QUERY_PRIMITIVE_AMBIGUOUS,
        QUERY_PRIMITIVE_UNRESOLVED,
        QUERY_SUBJECT_AMBIGUOUS,
        QUERY_SUBJECT_REQUIRED,
        QUERY_FRR_MISSING,
        QUERY_FEATURE_MISSING,
        QUERY_NOT_FOUND,
        QUERY_MATCH_ALL_CONFLICT,
        QUERY_INTERNAL,
        QUERY_DB_NOT_READY,
    }
)
