# Transformation Language Grammar v1.0 (normative sketch; validator is authoritative)

Expression   ::= Call
Call         ::= OperatorId "(" [ ArgList ] ")"
ArgList      ::= Arg ( "," Arg )*
Arg          ::= Ident "=" Value
Value        ::= Call | PrimitiveId | FeatureId | Literal | List
Literal      ::= IntLit | FloatLit | BoolLit | StringLit
List         ::= "[" [ Value ( "," Value )* ] "]"
OperatorId   ::= "OP_" Name
PrimitiveId  ::= "PR_" Name
FeatureId    ::= "FEAT_" Hex32
Name         ::= [A-Z][A-Z0-9_]*
Hex32        ::= [0-9A-F]{32}
Ident        ::= [a-z][a-z0-9_]*
IntLit       ::= "-"? [0-9]+
FloatLit     ::= "-"? [0-9]+ "." [0-9]+
BoolLit      ::= "true" | "false"
StringLit    ::= '"' { Char } '"'
