"""Lineage validation error-code constants (Sprint 7)."""

from __future__ import annotations

REL_SEED_HASH_MISMATCH = "REL_SEED_HASH_MISMATCH"
REL_INCOMPLETE = "REL_INCOMPLETE"
REL_EXTRA = "REL_EXTRA"
REL_INACTIVE = "REL_INACTIVE"
LINEAGE_ID_MISMATCH = "LINEAGE_ID_MISMATCH"
DUPLICATE_EDGE = "DUPLICATE_EDGE"
SELF_EDGE = "SELF_EDGE"
INVALID_OBJECT_REF = "INVALID_OBJECT_REF"
OBJECT_NOT_FOUND = "OBJECT_NOT_FOUND"
UNKNOWN_RELATIONSHIP = "UNKNOWN_RELATIONSHIP"
FREE_TEXT_RELATIONSHIP = "FREE_TEXT_RELATIONSHIP"
CYCLE_DETECTED = "CYCLE_DETECTED"
CHECKSUM_MISMATCH = "CHECKSUM_MISMATCH"
LINEAGE_VERSION_MISMATCH = "LINEAGE_VERSION_MISMATCH"
INVALID_EDGE_SOURCE = "INVALID_EDGE_SOURCE"
ORPHAN_NODE = "ORPHAN_NODE"

ALL_ERROR_CODES: frozenset[str] = frozenset(
    {
        REL_SEED_HASH_MISMATCH,
        REL_INCOMPLETE,
        REL_EXTRA,
        REL_INACTIVE,
        LINEAGE_ID_MISMATCH,
        DUPLICATE_EDGE,
        SELF_EDGE,
        INVALID_OBJECT_REF,
        OBJECT_NOT_FOUND,
        UNKNOWN_RELATIONSHIP,
        FREE_TEXT_RELATIONSHIP,
        CYCLE_DETECTED,
        CHECKSUM_MISMATCH,
        LINEAGE_VERSION_MISMATCH,
        INVALID_EDGE_SOURCE,
        ORPHAN_NODE,
    }
)
