"""Frozen REL_* relationship seed pack (Sprint 7 pack 1.0.0)."""

from __future__ import annotations

import hashlib
from typing import NamedTuple

from feature_intelligence.lineage.models import (
    LINEAGE_VERSION,
    REL_DEPENDS_ON,
    REL_DERIVED_FROM,
    REL_GENERATED_BY,
    REL_INPUT_TO,
    REL_USES,
    RELATIONSHIP_PACK_VERSION,
)

__all__ = [
    "LINEAGE_VERSION",
    "RELATIONSHIP_PACK_VERSION",
    "SEED_RELATIONSHIPS",
    "EXPECTED_RELATIONSHIP_SEED_HASH",
    "compute_relationship_seed_hash",
    "canonical_relationship_seed_document",
]


class SeedRelationship(NamedTuple):
    relationship_id: str
    canonical_name: str
    display_name: str
    description: str
    lineage_version: str
    active: int
    sort_order: int | None


def _r(
    rid: str,
    canonical: str,
    display: str,
    desc: str,
    sort: int,
) -> SeedRelationship:
    return SeedRelationship(
        relationship_id=rid,
        canonical_name=canonical,
        display_name=display,
        description=desc,
        lineage_version=LINEAGE_VERSION,
        active=1,
        sort_order=sort,
    )


SEED_RELATIONSHIPS: tuple[SeedRelationship, ...] = (
    _r(
        REL_USES,
        "uses",
        "Uses",
        "Parent is used in constructing child (typical: OP_* -> TR_*)",
        1,
    ),
    _r(
        REL_GENERATED_BY,
        "generated_by",
        "Generated By",
        "Parent generated child (typical: TR_* -> FEAT_*)",
        2,
    ),
    _r(
        REL_DEPENDS_ON,
        "depends_on",
        "Depends On",
        "Parent is a dependency of child (typical: FEAT_* -> TR_* feature-ref input)",
        3,
    ),
    _r(
        REL_DERIVED_FROM,
        "derived_from",
        "Derived From",
        "Child is derived from parent (typical: PR_* -> FEAT_* closure)",
        4,
    ),
    _r(
        REL_INPUT_TO,
        "input_to",
        "Input To",
        "Parent is an input into child (typical: PR_* -> TR_*)",
        5,
    ),
)


def canonical_relationship_seed_document(
    seeds: tuple[SeedRelationship, ...] | None = None,
) -> str:
    rows = sorted(seeds or SEED_RELATIONSHIPS, key=lambda r: r.relationship_id)
    lines: list[str] = []
    for r in rows:
        desc = r.description if r.description is not None else ""
        sort = "" if r.sort_order is None else str(r.sort_order)
        lines.append(
            f"{r.relationship_id}|{r.canonical_name}|{r.display_name}|"
            f"{desc}|{r.lineage_version}|{r.active}|{sort}"
        )
    return "\n".join(lines)


def compute_relationship_seed_hash(
    seeds: tuple[SeedRelationship, ...] | None = None,
) -> str:
    return hashlib.sha256(
        canonical_relationship_seed_document(seeds).encode("utf-8")
    ).hexdigest()


# Locked for pack 1.0.0 — bump only with intentional freeze change.
EXPECTED_RELATIONSHIP_SEED_HASH = (
    "37db7baf53e0ce16563e86c449301f047eb07d5be7b56a3f0c130610d4ed76be"
)
