"""Research validation error-code constants (Sprint 8)."""

from __future__ import annotations

FRR_ID_MISMATCH = "FRR_ID_MISMATCH"
MISSING_FRR = "MISSING_FRR"
DUPLICATE_FRR = "DUPLICATE_FRR"
ORPHAN_FRR = "ORPHAN_FRR"
FEATURE_NOT_FOUND = "FEATURE_NOT_FOUND"
INVALID_FEATURE_REF = "INVALID_FEATURE_REF"
INVALID_ONTOLOGY_REF = "INVALID_ONTOLOGY_REF"
INVALID_TRANSFORMATION_REF = "INVALID_TRANSFORMATION_REF"
INVALID_RESEARCH_STATUS = "INVALID_RESEARCH_STATUS"
INVALID_VALIDATION_STATUS = "INVALID_VALIDATION_STATUS"
EVIDENCE_COMPUTED = "EVIDENCE_COMPUTED"
INVALID_EXPERIMENT_IDS = "INVALID_EXPERIMENT_IDS"
RESEARCH_VERSION_MISMATCH = "RESEARCH_VERSION_MISMATCH"
CHECKSUM_MISMATCH = "CHECKSUM_MISMATCH"
PR_OP_TR_FRR_FORBIDDEN = "PR_OP_TR_FRR_FORBIDDEN"
INVALID_RECORD_SOURCE = "INVALID_RECORD_SOURCE"

ALL_ERROR_CODES: frozenset[str] = frozenset(
    {
        FRR_ID_MISMATCH,
        MISSING_FRR,
        DUPLICATE_FRR,
        ORPHAN_FRR,
        FEATURE_NOT_FOUND,
        INVALID_FEATURE_REF,
        INVALID_ONTOLOGY_REF,
        INVALID_TRANSFORMATION_REF,
        INVALID_RESEARCH_STATUS,
        INVALID_VALIDATION_STATUS,
        EVIDENCE_COMPUTED,
        INVALID_EXPERIMENT_IDS,
        RESEARCH_VERSION_MISMATCH,
        CHECKSUM_MISMATCH,
        PR_OP_TR_FRR_FORBIDDEN,
        INVALID_RECORD_SOURCE,
    }
)
